import pytest

from sppl import SPPLCommands
from sppl.spec import COMMANDS


DOCUMENTED_COMMAND_CODES = {
    "SPCSDT",
    "SPCGDT",
    "SPCSNC",
    "SPCGNC",
    "SPCSSC",
    "SPCGSC",
    "SPCSPS",
    "SPCGPS",
    "SPCSPD",
    "SPCGPD",
    "SPCSDV",
    "SPCGDV",
    "SPCSPR",
    "SPCGPR",
    "SPCSHP",
    "SPCGHP",
    "SPCSVP",
    "SPCGVP",
    "SPCSMO",
    "SPCGMO",
    "SPCSRS",
    "SPCGRS",
    "SPCSIC",
    "SPCGIC",
    "SPCSTC",
    "SPCGTC",
    "SPCSAS",
    "SPCGAS",
    "SPCSSP",
    "SPCGSP",
    "SPCSPA",
    "SPCGPA",
    "SPCSSL",
    "SPCGSL",
    "SPCSAP",
    "SPCGAP",
    "SPCSFS",
    "SPCSPM",
    "SPCGPM",
    "SPLTDS",
    "SPLLTF",
    "SPLGAT",
    "SPLGST",
    "SPLGSD",
    "SPLCDF",
    "SPLDTF",
    "SPLDTA",
    "SPLDDF",
    "SPLDDA",
    "SPLCDB",
    "SPLGFN",
    "SPLGFV",
    "SPLAQD",
    "SPLAMQ",
    "SPLGQC",
    "SPLGMQ",
    "SPLCQD",
    "SPLCMQ",
    "SPMCTV",
    "SPMCBV",
    "SPMC2D",
    "SPMCCV",
    "SPMCLV",
    "SPMCSV",
    "SPPSAP",
    "SPPSLQ",
    "SPPGLQ",
    "SPCGLQ",
    "SPPSTP",
    "SPPOTP",
    "SPPSTA",
    "SPGSUM",
    "SPGRES",
    "SPGGTP",
    "SPGGFW",
    "SPGGFV",
    "SPGGRR",
    "SPGGSN",
    "SPGGCP",
    "SPGSLI",
    "SPGGLI",
    "SPTSPS",
    "SPTGPS",
    "SPTSPC",
    "SPTGPC",
    "SPTSPP",
    "SPTGPP",
    "SPTSPD",
    "SPTGPD",
    "SPTSPA",
    "SPTGPA",
    "SPTSTP",
    "SPTGTP",
}


COMMAND_CASES = {
    "SPCSDT": (lambda c: c.set_system_datetime(25, 1, 2015, 11, 36, 0, 0), "~SPCSDT{25>1>2015>11>36>0>0}^"),
    "SPCGDT": (lambda c: c.get_system_datetime(), "~SPCGDT^"),
    "SPCSNC": (lambda c: c.set_network_configuration("192.168.1.123", "255.255.255.0", "192.168.1.1", 9100), "~SPCSNC{192.168.1.123>255.255.255.0>192.168.1.1>9100}^"),
    "SPCGNC": (lambda c: c.get_network_configuration(), "~SPCGNC^"),
    "SPCSSC": (lambda c: c.set_rs232_configuration(115200, "None", 8, 1), "~SPCSSC{115200>None>8>1}^"),
    "SPCGSC": (lambda c: c.get_rs232_configuration(), "~SPCGSC^"),
    "SPCSPS": (lambda c: c.set_print_speed(200), "~SPCSPS{200}^"),
    "SPCGPS": (lambda c: c.get_print_speed(), "~SPCGPS^"),
    "SPCSPD": (lambda c: c.set_print_delay(10), "~SPCSPD{10}^"),
    "SPCGPD": (lambda c: c.get_print_delay(), "~SPCGPD^"),
    "SPCSDV": (lambda c: c.set_darkness(100), "~SPCSDV{100}^"),
    "SPCGDV": (lambda c: c.get_darkness(), "~SPCGDV^"),
    "SPCSPR": (lambda c: c.set_print_rotation(180), "~SPCSPR{180}^"),
    "SPCGPR": (lambda c: c.get_print_rotation(), "~SPCGPR^"),
    "SPCSHP": (lambda c: c.set_horizontal_position(0), "~SPCSHP{0}^"),
    "SPCGHP": (lambda c: c.get_horizontal_position(), "~SPCGHP^"),
    "SPCSVP": (lambda c: c.set_vertical_position(5), "~SPCSVP{5}^"),
    "SPCGVP": (lambda c: c.get_vertical_position(), "~SPCGVP^"),
    "SPCSMO": (lambda c: c.set_mirroring_option(0), "~SPCSMO{0}^"),
    "SPCGMO": (lambda c: c.get_mirroring_option(), "~SPCGMO^"),
    "SPCSRS": (lambda c: c.set_ribbon_save_mode(0, 2, 4), "~SPCSRS{0>2>4}^"),
    "SPCGRS": (lambda c: c.get_ribbon_save_mode(), "~SPCGRS^"),
    "SPCSIC": (lambda c: c.set_internal_contact_mode(1, 100), "~SPCSIC{1>100}^"),
    "SPCGIC": (lambda c: c.get_internal_contact_mode(), "~SPCGIC^"),
    "SPCSTC": (lambda c: c.set_trigger_contact_mode(1, 3, 100), "~SPCSTC{1>3>100}^"),
    "SPCGTC": (lambda c: c.get_trigger_contact_mode(), "~SPCGTC^"),
    "SPCSAS": (lambda c: c.set_all_settings(300, 2, 100, 0, 1, 0, 0, 30, 1, 3, 60), "~SPCSAS{300>2>100>0>1>0>0>30>1>3>60}^"),
    "SPCGAS": (lambda c: c.get_all_settings(), "~SPCGAS^"),
    "SPCSSP": (lambda c: c.set_system_parameter(1, 25), "~SPCSSP{1>25}^"),
    "SPCGSP": (lambda c: c.get_system_parameter(1), "~SPCGSP{1}^"),
    "SPCSPA": (lambda c: c.set_all_system_parameters([25, 27, 300, 200]), "~SPCSPA{25>27>300>200}^"),
    "SPCGPA": (lambda c: c.get_all_system_parameters(), "~SPCGPA^"),
    "SPCSSL": (lambda c: c.set_system_language("02"), "~SPCSSL{02}^"),
    "SPCGSL": (lambda c: c.get_system_language(), "~SPCGSL^"),
    "SPCSAP": (lambda c: c.set_administrator_password(123456), "~SPCSAP{123456}^"),
    "SPCGAP": (lambda c: c.get_administrator_password(), "~SPCGAP^"),
    "SPCSFS": (lambda c: c.return_to_factory_settings(), "~SPCSFS^"),
    "SPCSPM": (lambda c: c.set_print_request_message(0, "OK"), "~SPCSPM{0>OK}^"),
    "SPCGPM": (lambda c: c.get_print_request_message(), "~SPCGPM^"),
    "SPLTDS": (lambda c: c.create_template_data("<Template></Template>"), "~SPLTDS{<Template></Template>}^"),
    "SPLLTF": (lambda c: c.load_template_file("temp1_53.ronx"), "~SPLLTF{temp1_53.ronx}^"),
    "SPLGAT": (lambda c: c.get_active_template(), "~SPLGAT^"),
    "SPLGST": (lambda c: c.get_stored_templates(), "~SPLGST^"),
    "SPLGSD": (lambda c: c.get_stored_data_files(), "~SPLGSD^"),
    "SPLCDF": (lambda c: c.create_data_file("sample.csv", "abc\nbce\ncde"), "~SPLCDF{sample.csv~gt~abc\nbce\ncde}^"),
    "SPLDTF": (lambda c: c.delete_template_file("temp1_53.ronx"), "~SPLDTF{temp1_53.ronx}^"),
    "SPLDTA": (lambda c: c.delete_all_templates(), "~SPLDTA^"),
    "SPLDDF": (lambda c: c.delete_data_file("datafile1.csv"), "~SPLDDF{datafile1.csv}^"),
    "SPLDDA": (lambda c: c.delete_all_data_files(), "~SPLDDA^"),
    "SPLCDB": (lambda c: c.clear_data_buffer(), "~SPLCDB^"),
    "SPLGFN": (lambda c: c.get_field_names("temp1_53.rox"), "~SPLGFN{temp1_53.rox}^"),
    "SPLGFV": (lambda c: c.get_field_value("BatchNo"), "~SPLGFV{BatchNo}^"),
    "SPLAQD": (lambda c: c.append_queue_data("TextCSV", ["AB001", "AB002"]), "~SPLAQD{TextCSV~gt~AB001\nAB002}^"),
    "SPLAMQ": (lambda c: c.append_multi_queue_data({"PRDNAME": ["PR01", "PR02"], "BATCH NO": ["A01B", "A02B"]}), "~SPLAMQ{PRDNAME~gt~PR01\nPR02~gt~BATCH NO~gt~A01B\nA02B}^"),
    "SPLGQC": (lambda c: c.get_queue_capacity("TextCSV"), "~SPLGQC{TextCSV}^"),
    "SPLGMQ": (lambda c: c.get_multi_queue_capacity("PRDNAME", "BATCH NO"), "~SPLGMQ{PRDNAME~gt~BATCH NO}^"),
    "SPLCQD": (lambda c: c.clear_queue_data("TextCSV"), "~SPLCQD{TextCSV}^"),
    "SPLCMQ": (lambda c: c.clear_multi_queue_data("PRDNAME", "BATCH NO"), "~SPLCMQ{PRDNAME~gt~BATCH NO}^"),
    "SPMCTV": (lambda c: c.change_text_value("brand_txt", "SAVEMA"), "~SPMCTV{brand_txt~gt~SAVEMA}^"),
    "SPMCBV": (lambda c: c.change_barcode_value("barcodeno", "8691234567890"), "~SPMCBV{barcodeno~gt~8691234567890}^"),
    "SPMC2D": (lambda c: c.change_2d_barcode_value("qrcodeno", "savema12345"), "~SPMC2D{qrcodeno~gt~savema12345}^"),
    "SPMCCV": (lambda c: c.change_counter_value("counter1", "000055"), "~SPMCCV{counter1~gt~000055}^"),
    "SPMCLV": (lambda c: c.change_logo_value("productlogo", "/9j/4Q=="), "~SPMCLV{productlogo~gt~/9j/4Q==}^"),
    "SPMCSV": (lambda c: c.change_selected_values({"brand_txt": "SAVEMA", "qrcodeno": "savema12345"}), "~SPMCSV{brand_txt~gt~SAVEMA~gt~qrcodeno~gt~savema12345}^"),
    "SPPSAP": (lambda c: c.start_print(), "~SPPSAP^"),
    "SPPSLQ": (lambda c: c.set_limited_print_count(1000), "~SPPSLQ{1000}^"),
    "SPPGLQ": (lambda c: c.get_limited_print_count(), "~SPPGLQ^"),
    "SPCGLQ": (lambda c: c.get_limited_print_count(use_document_typo=True), "~SPCGLQ^"),
    "SPPSTP": (lambda c: c.stop_print(), "~SPPSTP^"),
    "SPPOTP": (lambda c: c.one_test_print(), "~SPPOTP^"),
    "SPPSTA": (lambda c: c.get_printer_status(), "~SPPSTA^"),
    "SPGSUM": (lambda c: c.send_user_message("Package finished. Please stop printer"), "~SPGSUM{Package finished. Please stop printer}^"),
    "SPGRES": (lambda c: c.general_response("950225"), "~SPGRES{950225}^"),
    "SPGGTP": (lambda c: c.get_total_print_count(), "~SPGGTP^"),
    "SPGGFW": (lambda c: c.get_firmware_version(use_document_typo=True), "~SPGGFW^"),
    "SPGGFV": (lambda c: c.get_firmware_version(), "~SPGGFV^"),
    "SPGGRR": (lambda c: c.get_remaining_ribbon(), "~SPGGRR^"),
    "SPGGSN": (lambda c: c.get_serial_number(), "~SPGGSN^"),
    "SPGGCP": (lambda c: c.get_current_print_count(), "~SPGGCP^"),
    "SPGSLI": (lambda c: c.set_lock_interface(True), "~SPGSLI{1}^"),
    "SPGGLI": (lambda c: c.get_lock_interface(), "~SPGGLI^"),
    "SPTSPS": (lambda c: c.set_pack_size(60), "~SPTSPS{60}^"),
    "SPTGPS": (lambda c: c.get_pack_size(), "~SPTGPS^"),
    "SPTSPC": (lambda c: c.set_traverse_print_count(5), "~SPTSPC{5}^"),
    "SPTGPC": (lambda c: c.get_traverse_print_count(), "~SPTGPC^"),
    "SPTSPP": (lambda c: c.set_print_position(10), "~SPTSPP{10}^"),
    "SPTGPP": (lambda c: c.get_print_position(), "~SPTGPP^"),
    "SPTSPD": (lambda c: c.set_pack_distance(50), "~SPTSPD{50}^"),
    "SPTGPD": (lambda c: c.get_pack_distance(), "~SPTGPD^"),
    "SPTSPA": (lambda c: c.set_printing_area(400), "~SPTSPA{400}^"),
    "SPTGPA": (lambda c: c.get_printing_area(), "~SPTGPA^"),
    "SPTSTP": (lambda c: c.set_all_traverse_parameters(60, 5, 10, 50, 400), "~SPTSTP{60>5>10>50>400}^"),
    "SPTGTP": (lambda c: c.get_all_traverse_parameters(), "~SPTGTP^"),
}


def test_catalog_contains_every_documented_command_code():
    assert set(COMMANDS) == DOCUMENTED_COMMAND_CODES


def test_every_documented_command_has_an_explicit_frame_case():
    assert set(COMMAND_CASES) == DOCUMENTED_COMMAND_CODES


@pytest.mark.parametrize("code", sorted(DOCUMENTED_COMMAND_CODES))
def test_all_available_command_frames(code):
    build, expected = COMMAND_CASES[code]

    assert str(build(SPPLCommands())) == expected

